package domain.iportadorExcel;

public enum TipoConsumo {
  GAS_NATURAL,
  DIESEL_GASOIL,
  KEROSENE,
  FUEL_OIL,
  NAFTA,
  CARBON,
  CARBON_LENIA,
  LENIA,
  COMBUSTIBLE_CONSUMIDO_GASOIL,
  COMBUSTIBLE_CONSUMIDO_GNC,
  COMBUSTIBLE_CONSUMIDO_NAFTA,
  ELECTRICIDAD,
  PRODUCTO_TRANSPORTADO,
  MEDIO_DE_TRANSPORTE,
  DISTANCIA_MEDIA,
  PESO_TOTAL;
}
