package impacto_ambiental.models.entities.calculadorHC;

public enum TipoActividadDA{
  COMBUSTION_FIJA,
  COMBUSTION_MOVIL,
  ELECTRICIDAD_ADQUIRIDA_Y_CONSUMIDA,
  LOGISTICA_DE_PRODUCTOS_Y_RESIDUOS,
  TRANSPORTE_PUBLICO,
  TRANSPORTE_PARTICULAR,
  SERVICIO_CONTRATADO,
  SERVICIO_ECOLOGICO;
}
